# Generated by Django 6.0.7 on 2026-07-28 00:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0003_venta_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único para idempotencia', unique=True)),
                ('estado_emision', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIANDO', 'Enviando'), ('ACEPTADA', 'Aceptada por SUNAT'), ('RECHAZADA', 'Rechazada por SUNAT'), ('ERROR', 'Error de comunicación')], default='PENDIENTE', max_length=20)),
                ('serie', models.CharField(blank=True, max_length=4)),
                ('correlativo', models.IntegerField(blank=True, null=True)),
                ('enlace_pdf', models.URLField(blank=True, max_length=500)),
                ('enlace_xml', models.URLField(blank=True, max_length=500)),
                ('enlace_cdr', models.URLField(blank=True, max_length=500)),
                ('hash_sunat', models.CharField(blank=True, max_length=200)),
                ('codigo_respuesta', models.CharField(blank=True, max_length=50)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('errores_api', models.TextField(blank=True, help_text='Raw error logs for debugging')),
                ('correo_enviado', models.BooleanField(default=False)),
                ('fecha_envio_correo', models.DateTimeField(blank=True, null=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante_electronico', to='caja.venta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
