# Generated by Django 6.0.7 on 2026-07-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del cliente'),
        ),
    ]
