# Generated by Django 6.0.7 on 2026-07-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_venta_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pos_numero_autorizacion',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Autorización'),
        ),
        migrations.AddField(
            model_name='venta',
            name='pos_operador',
            field=models.CharField(blank=True, max_length=50, verbose_name='Operador POS (ej. Niubiz)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='pos_tipo_tarjeta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de tarjeta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='pos_ultimos_digitos',
            field=models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos'),
        ),
    ]
