# Generated by Django 6.0.7 on 2026-07-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_lote_movimientoinventario_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_perecedero',
            field=models.BooleanField(default=False, verbose_name='¿Es perecedero?'),
        ),
    ]
